export type GeoPlace = { id: string; lat: number; lng: number; label: string };

const PLACES: GeoPlace[] = [
  { id: "af", lat: 33.9, lng: 67.7, label: "Afganistán" },
  { id: "al", lat: 41.2, lng: 20.2, label: "Albania" },
  { id: "dz", lat: 28.0, lng: 1.7, label: "Argelia" },
  { id: "ad", lat: 42.5, lng: 1.5, label: "Andorra" },
  { id: "ao", lat: -11.2, lng: 17.9, label: "Angola" },
  { id: "ar", lat: -38.4, lng: -63.6, label: "Argentina" },
  { id: "am", lat: 40.1, lng: 45.0, label: "Armenia" },
  { id: "au", lat: -25.3, lng: 133.8, label: "Australia" },
  { id: "at", lat: 47.5, lng: 14.6, label: "Austria" },
  { id: "az", lat: 40.1, lng: 47.6, label: "Azerbaiyán" },
  { id: "bs", lat: 25.0, lng: -77.4, label: "Bahamas" },
  { id: "bh", lat: 26.0, lng: 50.6, label: "Baréin" },
  { id: "bd", lat: 23.7, lng: 90.4, label: "Bangladés" },
  { id: "by", lat: 53.7, lng: 27.9, label: "Bielorrusia" },
  { id: "be", lat: 50.5, lng: 4.5, label: "Bélgica" },
  { id: "bz", lat: 17.2, lng: -88.5, label: "Belice" },
  { id: "bo", lat: -16.3, lng: -63.6, label: "Bolivia" },
  { id: "ba", lat: 43.9, lng: 17.7, label: "Bosnia" },
  { id: "bw", lat: -22.3, lng: 24.7, label: "Botsuana" },
  { id: "br", lat: -14.2, lng: -51.9, label: "Brasil" },
  { id: "bg", lat: 42.7, lng: 25.5, label: "Bulgaria" },
  { id: "kh", lat: 12.6, lng: 105.0, label: "Camboya" },
  { id: "cm", lat: 7.4, lng: 12.4, label: "Camerún" },
  { id: "ca", lat: 56.1, lng: -106.3, label: "Canadá" },
  { id: "cl", lat: -35.7, lng: -71.5, label: "Chile" },
  { id: "cn", lat: 35.9, lng: 104.2, label: "China" },
  { id: "co", lat: 4.6, lng: -74.3, label: "Colombia" },
  { id: "cr", lat: 9.7, lng: -83.8, label: "Costa Rica" },
  { id: "hr", lat: 45.1, lng: 15.2, label: "Croacia" },
  { id: "cu", lat: 21.5, lng: -77.8, label: "Cuba" },
  { id: "cy", lat: 35.1, lng: 33.4, label: "Chipre" },
  { id: "cz", lat: 49.8, lng: 15.5, label: "Chequia" },
  { id: "dk", lat: 56.3, lng: 9.5, label: "Dinamarca" },
  { id: "do", lat: 18.7, lng: -70.2, label: "República Dominicana" },
  { id: "ec", lat: -1.8, lng: -78.2, label: "Ecuador" },
  { id: "eg", lat: 26.8, lng: 30.8, label: "Egipto" },
  { id: "sv", lat: 13.8, lng: -88.9, label: "El Salvador" },
  { id: "ee", lat: 58.6, lng: 25.0, label: "Estonia" },
  { id: "et", lat: 9.1, lng: 40.5, label: "Etiopía" },
  { id: "fi", lat: 61.9, lng: 25.7, label: "Finlandia" },
  { id: "fr", lat: 46.2, lng: 2.2, label: "Francia" },
  { id: "de", lat: 51.2, lng: 10.5, label: "Alemania" },
  { id: "gh", lat: 7.9, lng: -1.0, label: "Ghana" },
  { id: "gr", lat: 39.1, lng: 21.8, label: "Grecia" },
  { id: "gt", lat: 15.8, lng: -90.2, label: "Guatemala" },
  { id: "hn", lat: 15.2, lng: -86.2, label: "Honduras" },
  { id: "hk", lat: 22.4, lng: 114.1, label: "Hong Kong" },
  { id: "hu", lat: 47.2, lng: 19.5, label: "Hungría" },
  { id: "is", lat: 64.9, lng: -19.0, label: "Islandia" },
  { id: "in", lat: 20.6, lng: 79.0, label: "India" },
  { id: "id", lat: -0.8, lng: 113.9, label: "Indonesia" },
  { id: "ir", lat: 32.4, lng: 53.7, label: "Irán" },
  { id: "iq", lat: 33.2, lng: 43.7, label: "Irak" },
  { id: "ie", lat: 53.1, lng: -8.2, label: "Irlanda" },
  { id: "il", lat: 31.0, lng: 34.9, label: "Israel" },
  { id: "it", lat: 41.9, lng: 12.6, label: "Italia" },
  { id: "jm", lat: 18.1, lng: -77.3, label: "Jamaica" },
  { id: "jp", lat: 36.2, lng: 138.3, label: "Japón" },
  { id: "jo", lat: 30.6, lng: 36.2, label: "Jordania" },
  { id: "kz", lat: 48.0, lng: 67.0, label: "Kazajistán" },
  { id: "ke", lat: -0.0, lng: 37.9, label: "Kenia" },
  { id: "kr", lat: 35.9, lng: 127.8, label: "Corea del Sur" },
  { id: "kw", lat: 29.3, lng: 47.5, label: "Kuwait" },
  { id: "lv", lat: 56.9, lng: 24.6, label: "Letonia" },
  { id: "lb", lat: 33.9, lng: 35.9, label: "Líbano" },
  { id: "ly", lat: 26.3, lng: 17.2, label: "Libia" },
  { id: "lt", lat: 55.2, lng: 23.9, label: "Lituania" },
  { id: "lu", lat: 49.8, lng: 6.1, label: "Luxemburgo" },
  { id: "my", lat: 4.2, lng: 101.9, label: "Malasia" },
  { id: "mt", lat: 35.9, lng: 14.4, label: "Malta" },
  { id: "mx", lat: 23.6, lng: -102.6, label: "México" },
  { id: "md", lat: 47.4, lng: 28.4, label: "Moldavia" },
  { id: "ma", lat: 31.8, lng: -7.1, label: "Marruecos" },
  { id: "mz", lat: -18.7, lng: 35.5, label: "Mozambique" },
  { id: "mm", lat: 21.9, lng: 95.9, label: "Myanmar" },
  { id: "np", lat: 28.4, lng: 84.1, label: "Nepal" },
  { id: "nl", lat: 52.1, lng: 5.3, label: "Países Bajos" },
  { id: "nz", lat: -40.9, lng: 174.9, label: "Nueva Zelanda" },
  { id: "ni", lat: 12.9, lng: -85.2, label: "Nicaragua" },
  { id: "ng", lat: 9.1, lng: 8.7, label: "Nigeria" },
  { id: "no", lat: 60.5, lng: 8.5, label: "Noruega" },
  { id: "om", lat: 21.5, lng: 55.9, label: "Omán" },
  { id: "pk", lat: 30.4, lng: 69.3, label: "Pakistán" },
  { id: "pa", lat: 8.5, lng: -80.8, label: "Panamá" },
  { id: "py", lat: -23.4, lng: -58.4, label: "Paraguay" },
  { id: "pe", lat: -9.2, lng: -75.0, label: "Perú" },
  { id: "ph", lat: 12.9, lng: 121.8, label: "Filipinas" },
  { id: "pl", lat: 51.9, lng: 19.1, label: "Polonia" },
  { id: "pt", lat: 39.4, lng: -8.2, label: "Portugal" },
  { id: "pr", lat: 18.2, lng: -66.6, label: "Puerto Rico" },
  { id: "qa", lat: 25.4, lng: 51.2, label: "Catar" },
  { id: "ro", lat: 45.9, lng: 24.9, label: "Rumanía" },
  { id: "ru", lat: 61.5, lng: 105.3, label: "Rusia" },
  { id: "sa", lat: 23.9, lng: 45.1, label: "Arabia Saudita" },
  { id: "sn", lat: 14.5, lng: -14.5, label: "Senegal" },
  { id: "rs", lat: 44.0, lng: 21.0, label: "Serbia" },
  { id: "sg", lat: 1.35, lng: 103.8, label: "Singapur" },
  { id: "sk", lat: 48.7, lng: 19.7, label: "Eslovaquia" },
  { id: "si", lat: 46.2, lng: 14.9, label: "Eslovenia" },
  { id: "za", lat: -30.6, lng: 22.9, label: "Sudáfrica" },
  { id: "es", lat: 40.5, lng: -3.7, label: "España" },
  { id: "lk", lat: 7.9, lng: 80.8, label: "Sri Lanka" },
  { id: "se", lat: 60.1, lng: 18.6, label: "Suecia" },
  { id: "ch", lat: 46.8, lng: 8.2, label: "Suiza" },
  { id: "tw", lat: 23.7, lng: 121.0, label: "Taiwán" },
  { id: "tz", lat: -6.4, lng: 34.9, label: "Tanzania" },
  { id: "th", lat: 15.9, lng: 100.9, label: "Tailandia" },
  { id: "tn", lat: 33.9, lng: 9.5, label: "Túnez" },
  { id: "tr", lat: 38.96, lng: 35.2, label: "Turquía" },
  { id: "ua", lat: 48.4, lng: 31.2, label: "Ucrania" },
  { id: "ae", lat: 23.4, lng: 53.8, label: "Emiratos Árabes Unidos" },
  { id: "gb", lat: 55.4, lng: -3.4, label: "Reino Unido" },
  { id: "us", lat: 37.1, lng: -95.7, label: "Estados Unidos" },
  { id: "uy", lat: -32.5, lng: -55.8, label: "Uruguay" },
  { id: "uz", lat: 41.4, lng: 64.6, label: "Uzbekistán" },
  { id: "ve", lat: 6.4, lng: -66.6, label: "Venezuela" },
  { id: "vn", lat: 14.1, lng: 108.3, label: "Vietnam" },
  { id: "zm", lat: -13.1, lng: 27.8, label: "Zambia" },
  { id: "zw", lat: -19.0, lng: 29.2, label: "Zimbabue" },
  { id: "lima", lat: -12.05, lng: -77.04, label: "Lima" },
  { id: "arequipa", lat: -16.41, lng: -71.54, label: "Arequipa" },
  { id: "cusco", lat: -13.53, lng: -71.97, label: "Cusco" },
  { id: "bogota", lat: 4.71, lng: -74.07, label: "Bogotá" },
  { id: "medellin", lat: 6.25, lng: -75.56, label: "Medellín" },
  { id: "cdmx", lat: 19.43, lng: -99.13, label: "CDMX" },
  { id: "guadalajara", lat: 20.66, lng: -103.35, label: "Guadalajara" },
  { id: "monterrey", lat: 25.67, lng: -100.31, label: "Monterrey" },
  { id: "saopaulo", lat: -23.55, lng: -46.63, label: "São Paulo" },
  { id: "riodejaneiro", lat: -22.91, lng: -43.17, label: "Río de Janeiro" },
  { id: "buenosaires", lat: -34.60, lng: -58.38, label: "Buenos Aires" },
  { id: "santiago", lat: -33.45, lng: -70.67, label: "Santiago" },
  { id: "quito", lat: -0.18, lng: -78.47, label: "Quito" },
  { id: "caracas", lat: 10.48, lng: -66.90, label: "Caracas" },
  { id: "madrid", lat: 40.42, lng: -3.70, label: "Madrid" },
  { id: "barcelona", lat: 41.39, lng: 2.17, label: "Barcelona" },
  { id: "lisbon", lat: 38.72, lng: -9.14, label: "Lisboa" },
  { id: "paris", lat: 48.86, lng: 2.35, label: "París" },
  { id: "london", lat: 51.51, lng: -0.13, label: "Londres" },
  { id: "berlin", lat: 52.52, lng: 13.41, label: "Berlín" },
  { id: "rome", lat: 41.90, lng: 12.50, label: "Roma" },
  { id: "nyc", lat: 40.71, lng: -74.01, label: "Nueva York" },
  { id: "miami", lat: 25.76, lng: -80.19, label: "Miami" },
  { id: "la", lat: 34.05, lng: -118.24, label: "Los Ángeles" },
  { id: "toronto", lat: 43.65, lng: -79.38, label: "Toronto" },
  { id: "singapore-city", lat: 1.35, lng: 103.82, label: "Singapur" },
  { id: "tokyo", lat: 35.68, lng: 139.69, label: "Tokio" },
  { id: "seoul", lat: 37.57, lng: 126.98, label: "Seúl" },
  { id: "dubai", lat: 25.20, lng: 55.27, label: "Dubái" },
];

const ALIASES: Record<string, string> = {
  afghanistan: "af", algeria: "dz", andorra: "ad", angola: "ao", argentina: "ar", armenia: "am",
  australia: "au", austria: "at", azerbaijan: "az", azerbaiyan: "az", bahamas: "bs", bahrain: "bh",
  barein: "bh", bangladesh: "bd", banglades: "bd", belarus: "by", bielorrusia: "by", belgium: "be",
  belgica: "be", belize: "bz", belice: "bz", bolivia: "bo", bosnia: "ba", botswana: "bw", botsuana: "bw",
  brazil: "br", brasil: "br", bulgaria: "bg", cambodia: "kh", camboya: "kh", cameroon: "cm", camerun: "cm",
  canada: "ca", chile: "cl", china: "cn", colombia: "co", "costa rica": "cr", croatia: "hr", croacia: "hr",
  cuba: "cu", cyprus: "cy", chipre: "cy", czechia: "cz", "czech republic": "cz", chequia: "cz",
  denmark: "dk", dinamarca: "dk", "dominican republic": "do", "republica dominicana": "do", ecuador: "ec",
  egypt: "eg", egipto: "eg", "el salvador": "sv", estonia: "ee", ethiopia: "et", etiopia: "et",
  finland: "fi", finlandia: "fi", france: "fr", francia: "fr", germany: "de", alemania: "de", ghana: "gh",
  greece: "gr", grecia: "gr", guatemala: "gt", honduras: "hn", "hong kong": "hk", hungary: "hu",
  hungria: "hu", iceland: "is", islandia: "is", india: "in", indonesia: "id", iran: "ir", iraq: "iq",
  irak: "iq", ireland: "ie", irlanda: "ie", israel: "il", italy: "it", italia: "it", jamaica: "jm",
  japan: "jp", japon: "jp", jordan: "jo", jordania: "jo", kazakhstan: "kz", kazajistan: "kz", kenya: "ke",
  kenia: "ke", korea: "kr", "south korea": "kr", "corea del sur": "kr", kuwait: "kw", latvia: "lv",
  letonia: "lv", lebanon: "lb", libano: "lb", libya: "ly", libia: "ly", lithuania: "lt", lituania: "lt",
  luxembourg: "lu", luxemburgo: "lu", malaysia: "my", malasia: "my", malta: "mt", mexico: "mx", mexicoo: "mx",
  moldova: "md", moldavia: "md", morocco: "ma", marruecos: "ma", mozambique: "mz", myanmar: "mm", nepal: "np",
  netherlands: "nl", holland: "nl", holanda: "nl", "paises bajos": "nl", "new zealand": "nz",
  "nueva zelanda": "nz", nicaragua: "ni", nigeria: "ng", norway: "no", noruega: "no", oman: "om",
  pakistan: "pk", panama: "pa", paraguay: "py", peru: "pe", philippines: "ph", filipinas: "ph",
  poland: "pl", polonia: "pl", portugal: "pt", "puerto rico": "pr", qatar: "qa", catar: "qa", romania: "ro",
  rumania: "ro", russia: "ru", rusia: "ru", "saudi arabia": "sa", "arabia saudita": "sa", senegal: "sn",
  serbia: "rs", singapore: "sg", singapur: "sg", slovakia: "sk", eslovaquia: "sk", slovenia: "si",
  eslovenia: "si", "south africa": "za", sudafrica: "za", spain: "es", espana: "es", "sri lanka": "lk",
  sweden: "se", suecia: "se", switzerland: "ch", suiza: "ch", taiwan: "tw", tanzania: "tz", thailand: "th",
  tailandia: "th", tunisia: "tn", tunez: "tn", turkey: "tr", turquia: "tr", ukraine: "ua", ucrania: "ua",
  uae: "ae", emirates: "ae", "united arab emirates": "ae", "emiratos arabes unidos": "ae", "united kingdom": "gb",
  uk: "gb", britain: "gb", inglaterra: "gb", "reino unido": "gb", "united states": "us", usa: "us",
  "estados unidos": "us", eeuu: "us", "ee uu": "us", uruguay: "uy", uzbekistan: "uz", venezuela: "ve",
  vietnam: "vn", zambia: "zm", zimbabwe: "zw", zimbabue: "zw",
  lima: "lima", arequipa: "arequipa", cusco: "cusco", cuzco: "cusco", bogota: "bogota", medellin: "medellin",
  "ciudad de mexico": "cdmx", "mexico city": "cdmx", cdmx: "cdmx", df: "cdmx", guadalajara: "guadalajara",
  monterrey: "monterrey", "sao paulo": "saopaulo", "rio de janeiro": "riodejaneiro",
  rio: "riodejaneiro", "buenos aires": "buenosaires", santiago: "santiago", quito: "quito", caracas: "caracas",
  madrid: "madrid", barcelona: "barcelona", lisbon: "lisbon", lisboa: "lisbon", paris: "paris",
  london: "london", londres: "london", berlin: "berlin", rome: "rome", roma: "rome", "new york": "nyc",
  "nueva york": "nyc", nyc: "nyc", miami: "miami", "los angeles": "la", toronto: "toronto", tokyo: "tokyo",
  tokio: "tokyo", seoul: "seoul", seul: "seoul", dubai: "dubai", dubái: "dubai",
};

const INDEX = new Map<string, GeoPlace>();
for (const place of PLACES) {
  INDEX.set(place.id, place);
  INDEX.set(fold(place.label), place);
}
for (const [alias, id] of Object.entries(ALIASES)) {
  const place = INDEX.get(id);
  if (place) INDEX.set(fold(alias), place);
}

export function fold(value: string) {
  return value.normalize("NFD").replace(/\p{M}/gu, "").toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
}

export function resolvePlace(value: unknown): GeoPlace | null {
  if (value == null || value === "") return null;
  const raw = String(value).trim();
  if (!raw) return null;
  const coord = raw.match(/^(-?\d+(?:\.\d+)?)\s*[,;]\s*(-?\d+(?:\.\d+)?)$/);
  if (coord) {
    return { id: raw, lat: Number(coord[1]), lng: Number(coord[2]), label: raw };
  }
  const exact = INDEX.get(fold(raw));
  if (exact) return exact;
  const iso = fold(raw);
  if (iso.length === 2 || iso.length === 3) {
    const byId = INDEX.get(iso);
    if (byId) return byId;
  }
  for (const place of PLACES) {
    const label = fold(place.label);
    if (label && (iso.includes(label) || label.includes(iso))) return place;
  }
  return null;
}
